name: Create GitHub Issue
on:
  repository_dispatch:
    types: [create-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ISSUE_CREATOR_TOKEN }}
          script: |
            const issueTitle = context.payload.title;
            const issueBody = context.payload.body;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
