name: Registration

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  register:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout repo
      uses: actions/checkout@v2.3.2
    - name: validate request
      run: |
          python validate_registration_request.py "${{ github.event.issue.body }}"
          echo "PY_EXIT=$?" >> $GITHUB_ENV
          if [ $PY_EXIT -eq 0 ]; then
            echo "COMMENT=user added successfully" >> $GITHUB_ENV
            cp users.json.new users.json
          else
            echo "COMMENT=a user already exists with that username" >> $GITHUB_ENV
          fi
    - name: push changes
      run: |
          if [ $PY_EXIT -eq 0 ]; then
            git config --global user.name "Solalunara"
            git config --global user.email "greenberg04@gmail.com"

            git add users.json users.json.new
            git commit -m "Added user"
            git push
          fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: close issue
      run: |
          gh issue close --comment "$COMMENT" ${{ github.event.issue.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
